# ToDo: move this to some DB
fake_users_db = {
    "test_user_small_1": {
        "username": "test_user_small_1",
        "full_name": "Test User Small 1",
        "email": "",
        "hashed_password": "$2b$12$huA3QsZPL5/Tx2OZEv4UmurhJq7DgUcieDA3kshwDuw/TIaeVWt2K",
        "disabled": False,
        "llm_enabled": True,
        "credits": 100,
    },
    "test_user_small_2": {
        "username": "test_user_small_2",
        "full_name": "Test User Small 2",
        "email": "",
        "hashed_password": "$2b$12$5S2sy3d4C2F.sy32UJzPZekC5ASyotgPOfmGzHwltvQ3KDBuikv8y",
        "disabled": False,
        "credits": 100,
    },
    "test_user_small_3": {
        "username": "test_user_small_3",
        "full_name": "Test User Small 3",
        "email": "",
        "hashed_password": "$2b$12$w9NzPGsf2qROsBJDentFheGMmUYapNtDBunAlIqlNoszsj0g6sHb6",
        "disabled": False,
        "credits": 100,
    },
    "test_user_small_4": {
        "username": "test_user_small_4",
        "full_name": "Test User Small 4",
        "email": "",
        "hashed_password": "$2b$12$XbxvzGpoMo1rIgh0vNA3kOUSCdT1XSXWHanm0bHpRaQtHmqXev7qe",
        "disabled": False,
        "credits": 100,
    },
    "test_user_small_5": {
        "username": "test_user_small_5",
        "full_name": "Test User Small 5",
        "email": "",
        "hashed_password": "$2b$12$KObQqWacmPEuHty0SUNtkOgMSS/MTnO3CbQk2rtZFrjLijoLve3Uu",
        "disabled": False,
        "credits": 100,
    },
    "test_user_small_6": {
        "username": "test_user_small_6",
        "full_name": "Test User Small 6",
        "email": "",
        "hashed_password": "$2b$12$tMCwkySCQmSrm6fhLnRAIOudBqqD0trJisE8J8bQZXXqqswOOeMIy",
        "disabled": False,
        "credits": 100,
    },
    "test_user_big_1": {
        "username": "test_user_big_1",
        "full_name": "Test User Big 1",
        "email": "",
        "hashed_password": "$2b$12$qhyIC4LCilL.LWoHcloZwuC88QhHWgnIciUXfK1GBvd.ijQfehXeW",
        "disabled": False,
        "credits": 1000,
    },
    "test_user_big_2": {
        "username": "test_user_big_2",
        "full_name": "Test User Big 2",
        "email": "",
        "hashed_password": "$2b$12$eL4Ql3O.1X6z4dtZnBUaPOLDeIE1528m/dbsmtoOaU2MHkgF4VyXu",
        "disabled": False,
        "credits": 1000,
    },
    "test_user_big_3": {
        "username": "test_user_big_3",
        "full_name": "Test User Big 3",
        "email": "",
        "hashed_password": "$2b$12$sB6UFzClVpHNr3xCYLHgVOh4J04n1hY.WsyAoza1S8JW22ssJkMbq",
        "disabled": False,
        "credits": 1000,
    },
    "test_user_big_4": {
        "username": "test_user_big_4",
        "full_name": "Test User Big 4",
        "email": "",
        "hashed_password": "$2b$12$eQ1Ud.cVAH4WRXtzeBXi7uh9kQG.h2bil4U2ceJ8st5uLZmu9pGXu",
        "disabled": False,
        "credits": 1000,
    },
    "test_user_huge_1": {
        "username": "test_user_huge_1",
        "full_name": "Test User Huge 1",
        "email": "",
        "hashed_password": "$2b$12$msOzEN7cmZt5mOurzgAA2O/RdzV7LsUlz6olwSD3W71l1BEyKJ5OG",
        "disabled": False,
        "credits": 50000,
    },
    "test_user_huge_2": {
        "username": "test_user_huge_2",
        "full_name": "Test User Huge 2",
        "email": "",
        "hashed_password": "$2b$12$M5YR3Uc21b5Z.C9f2kJTRuAJT5in1h7SYIO0viWtmX18B6r1qLcny",
        "disabled": False,
        "credits": 50000,
    },
    "test_user_huge_3": {
        "username": "test_user_huge_3",
        "full_name": "Test User Huge 3",
        "email": "",
        "hashed_password": "$2b$12$2nej2S5AjWWfA5s3SlEfouxEaOC7KuwpR/lDjWf.1w9gP58i8NqL.",
        "disabled": False,
        "credits": 50000,
    },
    "main_user": {
        "username": "main_user",
        "full_name": "Main user",
        "email": "",
        "hashed_password": "$2b$12$RzozrLuLGka0QsdqbvOxAePc2lISz8K6tSJMNnkotqc47AAK5aO3q",
        "disabled": False,
        "llm_enabled": True,
        "credits": 9999999999,
    },
}
